print("                                                                          ")
print("                                                                          ")
print("――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――")
print("                                                                          ")
print(BOLD + BLUE + UNDERLINE + "Cosmo Account Link Verification Bot is now Online!" + RESET)
print(WHITE + "• Join our discord server for support: " + GREEN + "https://discord.gg/RfTSBK6bsR")
print(WHITE + "• By using this bot you agree to all terms located here: " + GREEN + "https://atmtx.co/cosmo-terms")
print("                                                                          ")
print(BOLD + BLUE + UNDERLINE + "Important Information:" + RESET)
print(RED + "Leaking or redistributing this resource is not allowed. If you are found doing it,")
print(RED + "your license will be permanently disabled and you will be reported!")
print(RESET + "                                                                          ")
print("――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――")